pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:pathlit-inc/onepath-docs.git
          - cd onepath-docs.git
          - git push --mirror --force git@github.com:Pathlit-Inc/documentation.git
